spring:
  profiles:
    active:
    - stage
---
spring:
  profiles: local
  application:
    name: bolabeken-core
  datasource:
    url : jdbc:postgresql://localhost:5432/bolabeken-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    continue-on-error: true
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
    generate-ddl: true    
server:
  context-path: /
  port: 8063
logging:
  path: ./logs
  file: ${logging.path}/${spring.application.name}.log
  level:
   ROOT: ERROR
   com.bolabeken.core: INFO
#   org.springframework.web: DEBUG
---
spring:
  profiles: stage
  application:
    name: bolabeken-core
  datasource:
    url : jdbc:postgresql://ec2-23-23-247-222.compute-1.amazonaws.com:5432/dbfai7ole0epts?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
    username: zhivrqesorrymk
    password: fd8b16368cf717a930e4fe7321865c63c9d7ac1a7b6393597d3ab3d91d8a5321
    driver-class-name: org.postgresql.Driver
    continue-on-error: true
  jpa:
    show-sql: false
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
    generate-ddl: true    
server:
  context-path: /api
  port: 8061
logging:
  path: ./logs
  file: ${logging.path}/${spring.application.name}.log
  level:
   ROOT: ERROR
   com.bolabeken.core: INFO
#   org.springframework.web: DEBUG