spring:
  profiles:
    active:
    - stage
---
spring:
  profiles: local
  application:
    name: bolabeken-core
  datasource:
    url : jdbc:postgresql://localhost:5432/bolabeken-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    continue-on-error: true
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
    generate-ddl: true    
server:
  context-path: /
  port: 8063
logging:
  path: ./logs
  file: ${logging.path}/${spring.application.name}.log
  level:
   ROOT: ERROR
   com.bolabeken.core: INFO
#   org.springframework.web: DEBUG
---
spring:
  profiles: stage
  application:
    name: bolabeken-core
  datasource:
    url : jdbc:postgresql://dxvxswhhqpqqzj:a37113452871bcc89ee93c004152452ddd28092a039b0c0e7d2c345a032b9408@ec2-23-21-129-50.compute-1.amazonaws.com:5432/d8b1urg21gjuds?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
    username: dxvxswhhqpqqzj
    password: d8b1urg21gjuds
    driver-class-name: org.postgresql.Driver
    continue-on-error: true
  jpa:
    show-sql: false
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
    generate-ddl: true    
server:
  context-path: /api
  port: 8061
logging:
  path: ./logs
  file: ${logging.path}/${spring.application.name}.log
  level:
   ROOT: ERROR
   com.bolabeken.core: INFO
#   org.springframework.web: DEBUG